modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="swordupgreades"
version="1.0.0"
displayName="Sword Upgreades"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="skyla, MCreator"

[[dependencies.swordupgreades]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




